# Generated by Django 3.2.7 on 2021-10-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('exchange', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'get_latest_by': ['ticker'],
            },
        ),
    ]
